version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    networks:
      - microservices

  order-service:
    build: ./order-service
    ports:
      - "4002:4002"
    networks:
      - microservices

  payment-service:
    build: ./payment-service
    ports:
      - "4003:4003"
    networks:
      - microservices

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - order-service
      - payment-service
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
